"""create employees and events tables

Revision ID: 09c9507871ac
Revises: 
Create Date: 2026-08-29 22:21:51.564757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09c9507871ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.Column('normal_start_hour', sa.Integer(), nullable=False),
    sa.Column('normal_end_hour', sa.Integer(), nullable=False),
    sa.Column('typical_ip', sa.String(length=45), nullable=False),
    sa.Column('typical_location', sa.String(length=120), nullable=False),
    sa.Column('typical_login_frequency', sa.Integer(), nullable=False),
    sa.Column('typical_files_accessed', sa.Integer(), nullable=False),
    sa.Column('typical_data_transfer_bytes', sa.BigInteger(), nullable=False),
    sa.Column('behavior_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('source_location', sa.String(length=120), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_injected_anomaly', sa.Boolean(), nullable=False),
    sa.Column('scenario_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_employee_id'), 'events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_employee_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
