"""add anomaly scoring

Revision ID: 3ab50abd62d1
Revises: 09c9507871ac
Create Date: 2026-08-29 23:30:42.028207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ab50abd62d1'
down_revision: Union[str, Sequence[str], None] = '09c9507871ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_uuid', sa.Uuid(), nullable=False),
    sa.Column('detector_name', sa.String(length=80), nullable=False),
    sa.Column('detector_version', sa.String(length=30), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_uuid'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid', 'detector_name', 'detector_version', name='uq_anomaly_event_detector_version')
    )
    op.create_index(op.f('ix_anomaly_scores_anomaly_score'), 'anomaly_scores', ['anomaly_score'], unique=False)
    op.create_index(op.f('ix_anomaly_scores_event_uuid'), 'anomaly_scores', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_anomaly_scores_risk_level'), 'anomaly_scores', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_scores_risk_level'), table_name='anomaly_scores')
    op.drop_index(op.f('ix_anomaly_scores_event_uuid'), table_name='anomaly_scores')
    op.drop_index(op.f('ix_anomaly_scores_anomaly_score'), table_name='anomaly_scores')
    op.drop_table('anomaly_scores')
    # ### end Alembic commands ###
