"""
Schemas for SENTINEL's local AI investigation layer.

The AI layer receives evidence that has already been generated by
SENTINEL's deterministic detection, correlation, and investigation
pipeline.

The language model is responsible for analyst-oriented interpretation,
not for deciding whether an attack occurred.
"""

from datetime import datetime
from typing import Literal

from pydantic import (
    BaseModel,
    Field,
)


# ============================================================
# AI service status
# ============================================================

class AIServiceStatus(BaseModel):
    """
    Current availability of SENTINEL's optional local AI provider.
    """

    enabled: bool
    available: bool

    provider: Literal[
        "ollama"
    ] = "ollama"

    model: str

    message: str


# ============================================================
# Structured AI analyst content
# ============================================================

class AIInvestigationContent(BaseModel):
    """
    Evidence-grounded analyst interpretation returned by the
    local language model.

    This schema will also be used to validate model output before
    any generated content is returned to the frontend.
    """

    executive_assessment: str = Field(
        min_length=1,
    )

    why_suspicious: list[str]

    timeline_interpretation: str = Field(
        min_length=1,
    )

    investigation_priorities: list[str]

    containment_considerations: list[str]

    confidence: Literal[
        "LOW",
        "MEDIUM",
        "HIGH",
    ]

    limitations: list[str]


# ============================================================
# Public AI investigation response
# ============================================================

class AIInvestigationResponse(BaseModel):
    """
    Complete API response for an AI-assisted incident investigation.

    The wrapper deliberately exposes generation metadata so the
    dashboard can distinguish deterministic SENTINEL evidence from
    locally generated AI interpretation.
    """

    incident_id: str

    provider: Literal[
        "ollama"
    ] = "ollama"

    model: str

    generated_at: datetime

    generation_duration_ms: int = Field(
        ge=0,
    )

    grounded_on_deterministic_evidence: bool = True

    content: AIInvestigationContent


# ============================================================
# Evidence package metadata
# ============================================================

class AIEvidencePackageSummary(BaseModel):
    """
    Metadata describing the evidence supplied to the AI layer.

    This does not expose simulator ground truth. It represents only
    operational evidence already available to SENTINEL.
    """

    incident_id: str

    incident_type: str
    severity: str

    timeline_event_count: int = Field(
        ge=0,
    )

    key_finding_count: int = Field(
        ge=0,
    )

    investigation_step_count: int = Field(
        ge=0,
    )

    containment_action_count: int = Field(
        ge=0,
    )