"""
Generate correlated SENTINEL security incidents.

This is the batch/offline incident-generation entry point used by the
controlled benchmark.

Architecture
------------
IncidentCorrelationEngine
    -> produces deterministic IncidentCandidate objects

IncidentPersistenceService
    -> persists those candidates using the same lineage-aware persistence
       boundary used by SENTINEL's operational event processor

Important boundaries
--------------------
- Simulator ground-truth labels are never queried or used.
- No generative AI is called.
- Detector and correlation lineage are persisted explicitly.
- Deterministic investigation guidance is generated by the persistence layer.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import sys


# ============================================================
# Repository bootstrap
# ============================================================

PROJECT_ROOT = (
    Path(__file__)
    .resolve()
    .parents[1]
)

BACKEND_ROOT = (
    PROJECT_ROOT
    / "backend"
)


for path in (
    PROJECT_ROOT,
    BACKEND_ROOT,
):
    path_string = str(
        path
    )

    if (
        path_string
        not in sys.path
    ):
        sys.path.insert(
            0,
            path_string,
        )


# ============================================================
# Application imports
# ============================================================

from app.database.session import SessionLocal  # noqa: E402

from app.services.incident_correlation import (  # noqa: E402
    IncidentCorrelationEngine,
)

from app.services.incident_persistence import (  # noqa: E402
    IncidentPersistenceService,
)


# ============================================================
# Batch incident generation
# ============================================================

def generate_incidents() -> None:
    """
    Correlate all selected-detector benchmark scores and persist
    resulting incidents through SENTINEL's canonical persistence layer.

    The caller receives console output only. This function owns the
    transaction for this one-shot batch command.
    """

    db = SessionLocal()

    try:
        # ----------------------------------------------------
        # Deterministic correlation
        # ----------------------------------------------------

        correlation_engine = (
            IncidentCorrelationEngine(
                db=db,
            )
        )

        candidates = (
            correlation_engine
            .correlate()
        )


        # ----------------------------------------------------
        # Canonical persistence
        # ----------------------------------------------------

        persistence_service = (
            IncidentPersistenceService(
                db=db,
            )
        )


        created = 0
        updated = 0

        incident_type_counts: Counter[
            str
        ] = Counter()

        severity_counts: Counter[
            str
        ] = Counter()


        for candidate in candidates:
            result = (
                persistence_service
                .persist_candidate(
                    candidate=candidate,
                )
            )


            if (
                result.action
                == "CREATED"
            ):
                created += 1

            elif (
                result.action
                == "UPDATED"
            ):
                updated += 1

            else:
                raise RuntimeError(
                    (
                        "Unexpected incident "
                        "persistence action: "
                        f"{result.action}"
                    )
                )


            incident = (
                result.incident
            )


            incident_type_counts[
                incident.incident_type
            ] += 1


            severity_counts[
                incident.severity
            ] += 1


        # ----------------------------------------------------
        # Atomic batch commit
        # ----------------------------------------------------

        db.commit()


        # ----------------------------------------------------
        # Report
        # ----------------------------------------------------

        print()

        print(
            "SENTINEL incident correlation complete."
        )

        print(
            "=" * 72
        )


        print(
            f"Incident candidates     : "
            f"{len(candidates)}"
        )

        print(
            f"New incidents           : "
            f"{created}"
        )

        print(
            f"Updated incidents       : "
            f"{updated}"
        )


        print()

        print(
            "Incident Type Distribution"
        )

        print(
            "-" * 72
        )


        for (
            incident_type,
            count,
        ) in sorted(
            incident_type_counts.items()
        ):
            print(
                f"{incident_type:<38}"
                f"{count:>6}"
            )


        print()

        print(
            "Severity Distribution"
        )

        print(
            "-" * 72
        )


        for (
            severity,
            count,
        ) in sorted(
            severity_counts.items()
        ):
            print(
                f"{severity:<16}"
                f"{count:>6}"
            )


        print(
            "=" * 72
        )


    except Exception:
        db.rollback()
        raise


    finally:
        db.close()


if __name__ == "__main__":
    generate_incidents()